spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    #data: classpath:data-h2.sql # 시작할때 실행시킬 script
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
#        url: jdbc:postresql://haru-postgresql.cgtz5bon0h1u.ap-northeast-2.rds.amazonaws.com:5432/haruDB
#        username: rhep0820
#        password: 
#        driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
  mustache:
    suffix: .html
    expose-session-attributes: true
      
banner:
  location: banner.txt
  